import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Workshop - Bí Mật Sắp Được Bật Mí',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <link
        rel='shortcut icon'
        href='./logo.png'
        type='image/png'
      />
      <meta
        property='og:image'
        content={`https://images.pexels.com/photos/3799821/pexels-photo-3799821.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500`}
      ></meta>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
